### ISSUE TITLE
import fails with basic host-template but 'alignak-arbiter -V' throws no exception

### ISSUE THREAD

**Issue by conrad784** [Alignak-monitoring-contrib/alignak-backend-import#80]
with following host-template the import tool fails to add it to the backend
`define host{`
`       name                             compute-server`
`      register                     0`
`       _wsp_load_peak_crit          40`
`       _wsp_load_peak_warn          10`
`}`

\- importing host template #3: compute-server
\# Post/patch error for: host : {'check_period': u'59428fb47f9b3a557fd27341', 'maintenance_period': u'59428fb47f9b3a557fd27342', 'service_includes': [], '_is_template': True, 'name': u'compute-server', 'snapshot_period': u'59428fb47f9b3a557fd27342', 'notification_period': u'59428fb47f9b3a557fd27341', 'check_command': '', 'customs': {u'_WSP_LOAD_PEAK_CRIT': u'40', u'_WSP_LOAD_PEAK_WARN': u'10'}, '_sub_realm': True, 'imported_from': 'alignak-backend-import', 'location': {'type': 'Point', 'coordinates': [48.858293, 2.294601]}, 'service_excludes': [], '_realm': u'59428fb47f9b3a557fd2733d'}
***** Exception: Backend error code 422: Insertion failure: 1 document(s) contain(s) error(s), response: {u'_status': u'ERR', u'_issues': {u'check_command': u"value 'None' must exist in resource 'command', field '_id'.", u'event_handler': u"value 'None' must exist in resource 'command', field '_id'."}, u'_error': {u'message': u'Insertion failure: 1 document(s) contain(s) error(s)', u'code': 422}}
***** %s Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/alignak_backend_import/cfg_to_backend.py", line 1962, in manage_resource
    response = self.backend.post(r_name, item, headers=None)
  File "/usr/lib/python2.7/dist-packages/alignak_backend_client/client.py", line 552, in post
    raise BackendException(error['code'], error['message'], resp)
BackendException: Backend error code 422: Insertion failure: 1 document(s) contain(s) error(s), response: {u'_status': u'ERR', u'_issues': {u'check_command': u"value 'None' must exist in re\
source 'command', field '_id'.", u'event_handler': u"value 'None' must exist in resource 'command', field '_id'."}, u'_error': {u'message': u'Insertion failure: 1 document(s) contain(s) error(s)', u'code': 422}}

***** response: {u'_status': u'ERR', u'_issues': {u'check_command': u"value 'None' must exist in resource 'command', field '_id'.", u'event_handler': u"value 'None' must exist in resource 'command', field '_id'."}, u'_error': {u'message': u'Insertion failure: 1 document(s) contain(s) error(s)', u'code': 422}}
~~~~~~~~~~~~~~~~~~~~~~~~~~
Exiting with error code: 5

**Comment by mohierf** [comment]
Thanks for reporting. The error is because you do not have defined a `check_command` nor an `event_handler` and those properties are valued with `None` that is not a valid value ... as a workaround, you must define both properties for your host (eg. _internal_host_up is a valid command that always returns 0/UP).

**Comment by mohierf** [comment]
Should be fixed now. Please re-open if the problem persists
